// <auto-generated />
using BlazorECommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorECommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorECommerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video Games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "《三国演义》是元末明初小说家罗贯中根据陈寿《三国志》和裴松之注解以及民间三国故事传说经过艺术加工创作而成的长篇章回体历史演义小说。",
                            ImageUrl = "https://img.zcool.cn/community/01848c6031ccc011013ef90f6b3643.png@2o.png",
                            Price = 9.99m,
                            Title = "《三国演义》"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "《西游记》是明代吴承恩创作的中国古代第一部浪漫主义章回体长篇神魔小说。",
                            ImageUrl = "https://img.zcool.cn/community/01c56d6031ccc011013f3745e2d03d.png@1280w_1l_2o_100sh.png",
                            Price = 7.99m,
                            Title = "《西游记》"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "《水浒传》是元末明初施耐庵（现存刊本署名大多有施耐庵、罗贯中两人中的一人，或两人皆有）编著的章回体长篇小说。",
                            ImageUrl = "https://img.zcool.cn/community/0100bc6031ccc111013ef90f03d56c.png@2o.png",
                            Price = 6.99m,
                            Title = "《水浒传》"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "《肖申克的救赎》The Shawshank Redemption 1994年这部被称为《刺激1995》的影片在中国影迷间也有极好的口碑，可见电影超越国界的神奇之处。",
                            ImageUrl = "http://img.doooor.com/img/forum/201706/23/022945t2ceojyziumuo85i.jpg",
                            Price = 6.99m,
                            Title = "《肖申克的救赎》"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "《教父》The Godfather 1972年科波拉黑帮经典《教父》的首部，派拉蒙公司最成功的影片之一，坐稳IMDB头把交椅应属众望所归。",
                            ImageUrl = "https://pic4.zhimg.com/v2-9db4ffdf47e979da4dd812ea09840162_qhd.jpg",
                            Price = 6.99m,
                            Title = "《教父》"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "《辛德勒的名单》Schindler's List 1993年斯皮尔伯格在《大白鲨》、《夺宝奇兵》、《外星人》、《紫色》四次与奥斯卡失之交臂后，终于在辛德勒和无数犹太难民的帮助下捧得金像。",
                            ImageUrl = "https://pic.baike.soso.com/p/20120928/20120928185404-62640921.jpg",
                            Price = 6.99m,
                            Title = "《辛德勒的名单》"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "《荒野大镖客：救赎2》是一款由《GTA5》、《荒野大镖客：救赎》团队打造开发的第三人称射击游戏。",
                            ImageUrl = "https://www.gamersky.com/showimage/id_gamersky.shtml?https://imgs.gamersky.com/ku/2018/ku_reddeadredemption_b.jpg",
                            Price = 6.99m,
                            Title = "《荒野大镖客》"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "《真三国无双7》登场武将均来自古代中国大陆魏、吴、蜀三个国家。魏晋重要人物也会登场，这不禁让人感慨故事将会是多么的复杂纠结。",
                            ImageUrl = "https://www.gamersky.com/showimage/id_gamersky.shtml?https://imgs.gamersky.com/ku/2013/ku_z357_b.jpg",
                            Price = 6.99m,
                            Title = "《真三国无双》"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "《使命召唤：战区2》是一款多人竞技类第一人称射击游戏，是《使命召唤：战区》的全新续作。",
                            ImageUrl = "https://www.gamersky.com/showimage/id_gamersky.shtml?https://imgs.gamersky.com/upimg/new_preview/2022/09/16/origin_b_202209161028006305_b.jpg",
                            Price = 6.99m,
                            Title = "《使命召唤》"
                        });
                });

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.HasOne("BlazorECommerce.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
